id: P58116414
initial_creation_type: input
source_metadata:
  Title: Nyāyapraveśapravṛtti
  Editor: Dhruva, A. B.
  Publisher: Sri Satguru Publications
  Place of Publication: India
  Year: '1987'
  Nyāyapraveśapravṛttiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:49:20.846123'
last_modified_at: '2022-03-08T16:49:20.846131'
